---
title: "Here are some plotly plots"
output: 
  html_document:
    theme: cosmo
---

# Interactivity is great


Loading the tidyverse
```{r, message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Loading the AirBNB dataseet.
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood, neighbourhood_group, rating, price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Let's make a scatterplot but an interactive one
```{r} 
nyc_airbnb |>  #learning plotly code
  mutate(
    label = str_c("Price: $", price, "\nRating: ", rating)
  ) |> 
  plot_ly( 
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5 #alpha makes color gradient
  )
```

Let's make a boxplot
```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x= ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box"
  )
```

Barcharts
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |> 
    plot_ly(
      x = ~neighbourhood, y = ~n,
      type = "bar")
```

ggPlotly: converting ggplot to interactive plotly. Not a good idea to use unless need to quickly convert ggplot
```{r}
ggp_scatterplot = 
  nyc_airbnb |> 
    ggplot(aes(x=lat, y=long, color=price)) +
    geom_point()

ggplotly(ggp_scatterplot)
```



